### ISSUE TITLE
Text only renders on macOS

### ISSUE THREAD

**Issue by seedrick** [derkyjadex/M8WebDisplay#15]
When I run the app on anything other than mac, the text doesn't display. I can move the cursor and everything actually works the way it's supposed to other than there being no text: 
![16484295869711223044673333463187](https://user-images.githubusercontent.com/15255246/160310134-b391142a-8823-4077-a195-5434bf3632ea.jpg)

This is running on an rpi4 but I get the same behavior in Windows. I've tried both Brave and Chrome and it works in Brave on mac.

EDIT: upon further testing, I find that it does work in Google Chrome proper on Windows. That's interesting since it works with other chromium based browsers on mac. I'm assuming it's the same problem with the rpi: no Chrome.

**Comment by m-hayabusa** [comment]
(armbian hirsute on DevTerm A04+ chromium-browser)
Same as above, but changing "Display Type" (in the hamburger menu) to "Canvas + SVG" from "WebGL2" makes rendered correctly for me.

**Comment by derkyjadex** [comment]
WebGL2 is newish, so it is possible that it is either not supported properly on your system or there are bugs. That said, it's not that new and I believe it is fully supported on Raspberry Pi 4 with an up-to-date OS.

To test this specifically, go to `chrome://gpu` (this should work in any Chrome based browser). That should show WebGL2 as "Hardware accelerated". If it doesn't then you'll have to fallback to using the "Canvas + SVG" display.

Also, make sure you don't have multiple tabs with the M8WebDisplay open at the same time, either in the same browser or different browsers. The display will be corrupted if that happens (the serial drawing commands get split between the multiple instances).
