### ISSUE TITLE
Browser on smart TV?

### ISSUE THREAD

**Issue by yentzee** [derkyjadex/M8WebDisplay#16]
Hi,
First of all thaks a lot for sharing your work. I had immediate success running it with a mac mini and a ps4 controller.
I was wondering whether it would be possible to use it on a browser on a smart tv.
If so you could have the teensy just being connected permanently to the back of the TV and make music instead of watching TV or playing games. Even with a treated studio it is quite nice to make some music just using a controller while sitting on the couch.
As I setup everything just yestrerday I was wondering whether it is possible to stream the audio to a connected bluetooth receiver. If not I suppose the audiostream can be routed there inside the OS of the host.
Oh also I was wondering whether there is any other way to get the audio when connected to a mobile running android. Did anyone try to connect devices to the teensys usb host port (the solderpads on top of the mcu)?

**Comment by derkyjadex** [comment]
Hi, whether it works on a smart TV would come down to what browser is on it. It would need to be based on a relatively up to date version of Chrome. The TV platform would also need to support serial over USB, or if it doesn't (in particular it won't if it is based on Android) then the WebUSB fallback might work.

I'm not sure how the audio works on a system like that, but if your Bluetooth output is set as the default if should work automatically. If the TV platform is Android based though, the audio will probably not work at all, unless Android TV handles things differently from the phone versions.

I think it *might* be possible to get audio directly off the Teensy if you connect up the right hardware, but it might not be available at all in the headless firmware. You'd have to ask around on Discord for more info.
