### ISSUE TITLE
Does it work with Chrome on iOS?

### ISSUE THREAD

**Issue by marcora** [derkyjadex/M8WebDisplay#17]

**Comment by derkyjadex** [comment]
I don't have any iOS devices to test with, but I believe that it does not work in any browser on iOS.

The specific API this project uses is Web Serial, which is not supported by Safari. Chrome for iOS (and every other browser for iOS) is simply a wrapper around the same engine that Safari uses. I *think* that APIs like Web Serial could be supported *in theory* but I could be wrong and I'm not aware of any attempt to do it.
