### ISSUE TITLE
Termux support

### ISSUE THREAD

**Issue by xyproto** [derkyjadex/M8WebDisplay#18]
`make` does not work on Termux, because there are not prebuilt packages available for `imagemin-optipng`.

Please consider also supporting Termux/Android.

**Comment by derkyjadex** [comment]
I suspect there won't be a simple drop in alternative for that specific package, but I can look at making that step optional. The committed images have already been processed as far as I remember, so that step isn't strictly necessary.

**Comment by xyproto** [comment]
That would be excellent! 🙂

**Comment by derkyjadex** [comment]
I ended up removing the whole imagemin dependency. Can you try out the latest changes and let me know whether it's working for you now?

**Comment by xyproto** [comment]
Thanks! It works now. It's pretty neat!

Here's a photo, using M8WebDisplay, Chrome and Teensy 4.1, where M8WebDisplay was git cloned and run from within the Termux application. Feel free to use it anywhere you want ([CC0, no rights reserved](https://creativecommons.org/share-your-work/public-domain/cc0/)).

![m8web](https://user-images.githubusercontent.com/52813/169787958-bbe8301f-7676-4bea-86f0-599198e70ed1.png)

**Comment by xyproto** [comment]
It also really works well with the on-screen controls! It would be nifty if they were shown by default for systems where `uname -o` returns `Android`.

This has the potential to be a great mobile setup. My dream is to use M8WebDisplay + Teensy 4.1 while commuting, until I can get my hands on a proper M8 device.

Right now, the audio does not seem to work, though. I can't hear any sounds in Chrome. Is there anything I can do to help pinpoint what the issue might be?

**Comment by derkyjadex** [comment]
I don't think I'd want to go down the route of changing the build output depending on the platform. The setting to show the on-screen controls is saved in local storage, so a default would only affect the very first time it is opened on a device. I think it is easy enough to just turn it on manually once.

The audio for Android is a known issue that I've described in the README. I'm not aware of any way of fixing it until Google changes the way that multiple audio devices are handled on Android and Chrome for Android. I have seen some suggestions for apps that can do this but I cannot get them to work myself.

**Comment by xyproto** [comment]
Ah, right. I missed that in the documentation.

Oh well, perhaps m8c which uses SDL2 is a better way to go on Android then.
