### ISSUE TITLE
Show visual feedback of keypresses on screen

### ISSUE THREAD

**Issue by gunnbr** [derkyjadex/M8WebDisplay#21]
There was a request in the M8 meetup today to have the web display give visual feedback of what keys are being pressed so that when someone is using the web display to stream M8, viewers can see what buttons are being pressed.

**Comment by derkyjadex** [comment]
Would that be on the on-screen keys? A brief flash of the blue outline you get when you click/touch the buttons? I think that wouldn't be too hard to do.

**Comment by derkyjadex** [comment]
Looks like GitHub decided to close this automatically based on my commit message. I haven't published the changes yet, but you can test out the change locally if you want and let me know what you think. Otherwise I should publish the updates in the next few days.

**Comment by gunnbr** [comment]
Wow! Fixed before I even had a chance to reply! I'll give it a try locally and see what I think...

**Comment by gunnbr** [comment]
Works great! I would say it may be just a little subtle though. It is easy to set the fill color for the button in blue when it's pressed instead of just the outline? Maybe I'm just used to the way it looks [in the official meetups](https://youtu.be/HwgAz21I8p8?t=170).

**Comment by derkyjadex** [comment]
I've updated the flash to fill the whole button and I've taken the colours from the manual/meetup videos. What do you think?

**Comment by gunnbr** [comment]
Awesome!!! Looks fantastic!!

**Comment by derkyjadex** [comment]
This has been published now.
