### ISSUE TITLE
Display version number

### ISSUE THREAD

**Issue by gunnbr** [derkyjadex/M8WebDisplay#22]
I think it would be useful to have a version number displayed somewhere, maybe on the About screen.
This came up when I told a streamer that you made key presses show on the on screen keyboard. It's not working for him, so I really would like to see a version number displayed so we can make sure we're both using the same version. If it's still not working, then we can figure out if it's different browsers or what.

**Comment by derkyjadex** [comment]
The latest release now includes a build number generated from the date and git commit hash. Displayed on the about screen.
