### ISSUE TITLE
Can't update firmware anymore

### ISSUE THREAD

**Issue by kikendo** [derkyjadex/M8WebDisplay#28]
Tried to update to version 3.1.1 today and it would not accept any Firmware file as a valid firmware file. Tried with 3.1.1, 3.1.0, 3.0.4, 3.0.3
This was working fine last time I updated.

**Comment by derkyjadex** [comment]
Can you confirm the error message you are getting? I am able to open the firmware files for 3.0.4, 3.1.0, 3.1.1 and 3.1.2 to get to the device selection screen.

If you are getting an error before that stage you should be able to get more details from the DevTools console (open with F12 before trying to open the firmware file). It will be helpful if you can paste any errors logged there into this issue so I can figure out where it is going wrong.

As a quick double-check that the files are valid, they should all be around 1.7MB. If they are a lot bigger or smaller than that then something may have gone wrong with the download.
