### ISSUE TITLE
Any idea if this would work on ARM Chromium? 

### ISSUE THREAD

**Issue by peterswimm** [derkyjadex/M8WebDisplay#3]
It looks like the page will load on a stock rasp pi 4, but it does not see the device.

**Comment by derkyjadex** [comment]
I think it should work in theory, as long as the browser supports the correct APIs. In particular, it needs to have the Web Serial API. That was introduced in Chrome 89. Do you know which version of Chromium you are running?

I don't have the right hardware to test on at the moment so I'm not able to look any further into it myself.

**Comment by peterswimm** [comment]
I'll give it a shot when I have a chance.

**Comment by JeffAlyanak** [comment]
I can confirm that this works without any hassle on my Linux arm system, but my user did require the correct permissions for the serial connection.

@peterswimm  On many Linux systems this will simply require you to add your user to the `dialout` group.

**Comment by peterswimm** [comment]
sounds great, closing as answered!
