### ISSUE TITLE
Keys for note entry

### ISSUE THREAD

**Issue by cpkcpkcpk** [derkyjadex/M8WebDisplay#4]
Hey, would it be possible to add keys for note entry, in the same way the TouchDesigner display uses A-L keys and +/- to switch octave?

Thanks

**Comment by derkyjadex** [comment]
I haven't really looked at this recently but I assume TouchDesigner is sending the notes via USB MIDI. It should certainly be possible to open the MIDI device and send note on/off messages on key down/up events.

I don't know if I'm likely to implement this myself any time soon, but feel free to have a go yourself and raise a pull request if you get it working.

**Comment by gunnbr** [comment]
I implemented this in my C# M8 display. It's quite easy to do and I have been meaning to try to add it to the M8WebDisplay. Hopefully I'll get some time to work on that soon...

**Comment by derkyjadex** [comment]
I've had a look at this and it turns out it's simpler than I was expecting (I forgot about the serial command to send notes). I've got something basic working. Should have a fully working version ready soonish.

**Comment by derkyjadex** [comment]
I've added this in the latest update. Works pretty much the same as the TouchDesigner version. Details are on the updated about screen.

**Comment by cpkcpkcpk** [comment]
Thanks so much for adding this!

**Comment by gunnbr** [comment]
Awesome! Thank you!!
